### ISSUE TITLE
cannot open in http://localhost:8080

### ISSUE THREAD

**Issue by selaphy** [eisman/neo4jd3#1]
when i input the commend "gulp", I get the error "events,js 141 throw er;// unhandled error event" and Error; Gem undefined is not installed. How can I fix this problem.

**Comment by eisman** [comment]
The project uses `gulp-ruby-sass` to convert `neo4jd3.scss` to `neo4jd3.css`, so you will need to install ruby and the sass gem (`gem install sass`). I have updated the README file to make it clear.

Please, let me know if you have any other problem.
