### ISSUE TITLE
How to reset the data with new data, not append.

### ISSUE THREAD

**Issue by BenDerPan** [eisman/neo4jd3#14]
I get new neo4j json data from websocket, and I want to repalce the old data with the new data, but updateWithNeo4jData or updateWithD3Data always append the new data to the old one , how can I clear the old data before it render the new ones?

**Comment by laaron2008** [comment]
@BenDerPan Could you tell me how to get neo4j json data?
Thank you

**Comment by BenDerPan** [comment]
you can get it from ajax or websocket , that means you need to build a web server which support json api(like resfFul API) or websockets first, and the server provide you the data you need for neo4j.

**Comment by blinkcat** [comment]
@BenDerPan Have you found a way to solve this problem？
I need your help.

**Comment by BenDerPan** [comment]
@blinkcat  sorry I have gave it up... maybe you can use d3.js to do so.

**Comment by jesusalber1** [comment]
New pull request to support this functionality #24 . It follows the same idea as _updateWithNeo4jData_ but it replaces the nodes and relationships instead of adding them to the current graph.

**Comment by blinkcat** [comment]
@jesusalber1   Nice work！Thanks.
