### ISSUE TITLE
Can i add custom label into node? 

### ISSUE THREAD

**Issue by laxen00** [eisman/neo4jd3#22]
@eisman Thanks for the neo4jd3 you make, very helpful for me, but can i add label for each node? 

thanks...

**Comment by bsridatta** [comment]
Hi @laxen00  I'm really new to the web and I'm trying to replicate this present visualization on my GitHub pages.I have forked and change the GitHub page settings. But it just keeps displaying nothing more than the README.md. I don't understand where I'm going wrong. Could you please tell me how? 
Thanks in advance :)

**Comment by mboussaa** [comment]
I need this as well @laxen00 how did you solve the problem?
