### ISSUE TITLE
Creating TypeScript Library

### ISSUE THREAD

**Issue by viveksacademia4git** [eisman/neo4jd3#54]
Hello @eisman I am going to create a TypeScript Library using the code from [neo4jd3.js](https://github.com/eisman/neo4jd3/blob/master/src/main/scripts/neo4jd3.js), since there is no code of support provided in this library

**Comment by viveksacademia4git** [comment]
I will post the library address once I am done maybe by end of this week. You are welcome contribute, I would really appreciate that.

**Comment by viveksacademia4git** [comment]
I have created the following library, lets hope that I may complete the initial working implementation by end of this week. Link [neo4jd3ts](https://github.com/vivopensource/neo4jd3ts)

**Comment by viveksacademia4git** [comment]
I was able to integrate it, in the Angular 8 successfully. I have lot of ideas and I would like to contribute to this project.

**Comment by auzair92** [comment]
Hi Vivek. I am trying to use Neo4j in my Angular 8 project as well, but don't know how to go about it. Can you please share the procedure?

**Comment by viveksacademia4git** [comment]
Hello,

I am going to prepare the Angular typescript library for this, in few days

**Comment by kerimovscreations** [comment]
Hi @viveksacademia4git , can you share your solution to solve the `ERROR ReferenceError: d3 is not defined` problem in Angular project?

**Comment by viveksacademia4git** [comment]
Hello @kerimovscreations and @auzair92 
I have created the new library by using this one as a fork.
URL of the test application which contains implementation steps is https://github.com/vivopensource/ng-neo4jd3-test

**Comment by kerimovscreations** [comment]
@viveksacademia4git thanks

**Comment by rugobal** [comment]
Hi @viveksacademia4git, what would be the process if I wanted to make some modifications to the neo4jd3.js javascript and include it within your Typescript libary? (https://github.com/vivopensource/ng-neo4jd3)

Meaning, to compile my own version of the library.

Thanks
